version: 2

defaults: &defaults
  working_directory: ~/symfony-circleci
  docker:
    - image: circleci/php:7.0-fpm-browsers

jobs:

  setup:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout

      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Add CircleCI parameter.yml file
          command: cp .circleci/parameters.yml.dist app/config/parameters.yml

      - run:
          command: sudo composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-vendors-{{ checksum "composer.json" }}
            - v1-vendors-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # Get new repo
      - run:
          name: Get deploy-trigger project
          command: |
            cd ~
            git clone git@github.com:sorinsugar/DCSRatingBundle.git
            ls -al

      # Persist project data
      - persist_to_workspace:
          root: ~/
          paths:
            - symfony-circleci
            - DCSRatingBundle

  tests:
    <<: *defaults
    parallelism: 1
    steps:
#      - attach_workspace:
#          at: ~/
      - run:
          name: Test location
          command: |
            pwd
            ls -al
            ls -al ~
            docker-compose --help

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup
      - tests:
          requires:
            - setup
