version: 2

# Setup variable
defaults: &setup
  working_directory: ~/symfony-circleci
  docker:
    - image: circleci/php:7.0-fpm-browsers

# Tests variable
defaults: &tests
  environment:
    DB_NAME: somedatabase
    DB_USER: root
    DB_PASS: root
    DB_PORT: 3306
    DB_HOST: 127.0.0.1
  working_directory: ~/symfony-circleci
  docker:
    - image: circleci/php:7.0-fpm-browsers
    - image: vouchedfor/main-db-sanitized-prod
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS

jobs:

  setup:
    <<: *setup
    parallelism: 1
    steps:
      - checkout

      - run:
          name: Run composer self-update
          command: sudo composer self-update

      - restore_cache:
          keys:
            - v1-vendors-{{ checksum "composer.json" }}
            - v1-vendors-

      - run:
          name: Run composer install
          command: composer install -n --prefer-dist

      - run:
          name: Copy parameters.yml
          command: |
            cat app/config/parameters.yml
            rm -f app/config/parameters.yml
            cp .circleci/parameters.yml.dist app/config/parameters.yml
            cat app/config/parameters.yml

      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # Persist project data
      - persist_to_workspace:
          root: ~/
          paths:
            - symfony-circleci
            - .ssh

  tests:
    <<: *tests
    parallelism: 1
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Wait for db
          command: dockerize -wait tcp://$DB_HOST:3306 -timeout 1m

#      - run:
#          name: Install mysql client
#          command: |
#            sudo apt-get update
#            sudo apt-get install -y mysql-client

      - run:
          name: Install php mysql extension
          command: |
            sudo docker-php-ext-install pdo_mysql

      - run:
          name: Export password and host
          command: |
            export DB_PORT=3306
            export DB_PASS=root

      - run:
          name: Run migrations
          command: php bin/console -n doctrine:database:create

      - run:
          name: Run migrations
          command: php bin/console -n doctrine:migrations:migrate

      - run:
          name: Run phpunit tests
          command: vendor/phpunit/phpunit/phpunit

  build:
    <<: *setup
    parallelism: 1
    steps:
      - attach_workspace:
          at: ~/

      - setup_remote_docker

      - run:
          name: Build  docker image
          command: |
            docker build -t sorinsugar/simfony-circleci:$CIRCLE_SHA1
            docker tag -f sorinsugar/simfony-circleci:$CIRCLE_SHA1 sorinsugar/simfony-circleci:latest

      - run:
          name: Push  docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push sorinsugar/simfony-circleci:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - /.*/
      - tests:
          requires:
            - setup
          filters:
            branches:
              only:
                - /.*/
      - build:
          requires:
            - tests
          filters:
            branches:
              only:
                - /master/
